// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnwuznxdnztasqeuemya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ud3V6bnhkbnp0YXNxZXVlbXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjIzOTAsImV4cCI6MjA2OTUzODM5MH0.p_NvI2zEyLSsR48bv08aztKO7olLDQg4Ib_BzqCRm88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});